### ISSUE TITLE
Footer: Made to play strip does not have URL

### ISSUE THREAD

**Issue by jeric888williamhill** [aemsites/888de#162]
Hi @helms-charity,

Please see bug details below:

Steps to Reproduce:
1. Access https://eds-www.888.de/
2. Navigate to the footer.
3. Hover or click the made to play strip.
4. Notice that the made to play strip does not have URL

<img width="951" alt="made to play" src="https://github.com/aemsites/888de/assets/165638341/a1e94d71-081a-4e07-8402-0a50096bd48a">

Note: As compared to original site, it should redirect to: https://www.888.de/sicherheit-datenschutz/verantwortungsbewusstes-spielen/

**Comment by dave-fink** [comment]
This has been fixed - please review.

**Comment by jeric888williamhill** [comment]
Hi @dave-fink,

This issue is partially fixed.
Notice that upon hovering the strip, it doesn't show a preview link in the lower left bottom of the screen.

**Comment by dave-fink** [comment]
This has been resolved - please retest.

**Comment by jeric888williamhill** [comment]
Hi @dave-fink,

Fixed verified.
Closing this issue.

Thanks!
