### ISSUE TITLE
Inner pages: Discrepancies in the 404 page

### ISSUE THREAD

**Issue by jeric888williamhill** [aemsites/888de#188]
Hi @helms-charity,

I have 2 issues on this page

Please see bug details below:

**1st issue:** Incorrect redirection of the CTAs

**Steps to Reproduce:**
1. Access 404 page. (e.g https://eds-www.888.de/123/)
2. Click on the CTA of 888slots, 888poker, and 888sport.
3. Notice that the CTA redirects to Canadian site.

<img width="969" alt="image" src="https://github.com/aemsites/888de/assets/165638341/77cbf20d-3215-4b27-be02-6508586cd4f8">

****2nd** issue:** The label of 888poker and 888sport CTA is incorrect

**Steps to Reproduce:**
1. Access 404 page. (e.g https://eds-www.888.de/123/)
2. Notice that the label of 888poker and 888sport CTA is incorrect. It should be "888poker herunterladen" for 888poker and "Bei 888sport anmelden" for 888sport as compared to original site. 

![image](https://github.com/aemsites/888de/assets/165638341/1666c041-d864-42f9-8338-296a81f577e4)

**Comment by helms-charity** [comment]
Hi Jeric, it seems this was only a content authoring issue, please test it again when you have a chance.

**Comment by jeric888williamhill** [comment]
HI @helms-charity,

New issue found.

The CTA opens a new tab instead of staying in the same tab.

![image](https://github.com/aemsites/888de/assets/165638341/0b5680e1-a8db-46e2-85db-7d29f4c6957d)

Please also redirect the CTAs based on the URL given in the original site.
888slots: https://www.888slots.de/registrieren/
888poker: https://www.888poker.de/download-poker/
888sport: https://www.888sport.de/?deeplink=opennrs

**Comment by dave-fink** [comment]
The links have been updated. Please revalidate.

**Comment by jeric888williamhill** [comment]
Hi @dave-fink,

Aside from the existing issue above, I would like to add this issue that happens in mobile devices.

Issue: The creative for the 404 page is too small compared with the original site making the word "oh je" overlaps with the 888 flag in the creatives. See screenshot below.

![image](https://github.com/aemsites/888de/assets/165638341/8cd82fb1-7946-4b70-ab71-5c1128cfedd3)

**Comment by kailasnadh790** [comment]
Styling issue is fixed. Please validate.

Issue with button redirections are related to https://github.com/aemsites/888de/issues/191#issuecomment-2043316748 .

**Comment by jeric888williamhill** [comment]
Fixed verified for styling issue.

Open issue:
No redirection link for all CTA

**Comment by kailasnadh790** [comment]
@jeric888williamhill Redirections are fixed. #191 is kept open to address GA events.

**Comment by jeric888williamhill** [comment]
@kailasnadh790,  CTAs in the 404 page still not clickable from my end.

**Comment by kailasnadh790** [comment]
@jeric888williamhill I have seen this issue with previously accessed error page URL...some kind of caching at 888 CDN is causing this. Can you try with a new "wrong URL" ?

https://github.com/aemsites/888de/assets/53608019/dac4928e-c43b-4d39-acb1-7c6d6e4a1da9

**Comment by jeric888williamhill** [comment]
Hi @kailasnadh790,
I see. Thanks for explaining it, now it works. Fixed/verified for this issue. Closing this now.
