### ISSUE TITLE
Homepage: There are no GA events for top banner/slider, offer boxes and login pop up

### ISSUE THREAD

**Issue by jeric888williamhill** [aemsites/888de#191]
Hi @helms-charity ,

Please see bug details below:

**Steps to Reproduce:**
1. Access https://eds-www.888.de/
2. Click any CTA in the image below.
3. Notice that there are no GA events present upon clicking the CTAs.

![image](https://github.com/aemsites/888de/assets/165638341/58d47eb3-e45e-4b0b-ae90-6ec1569ea072)

![image](https://github.com/aemsites/888de/assets/165638341/a27fe537-86e0-440d-b2c1-0193f0b421fa)

**Comment by kailasnadh790** [comment]
@jeric888williamhill I can see the events being tracked 
![image](https://github.com/aemsites/888de/assets/53608019/c0f9207d-f5c0-4300-b5e0-5dbb2401e73e)

what plugin you use to test these?

**Comment by jeric888williamhill** [comment]
Hi @kailasnadh790,

I'm using event tracking tracker plugin in chrome. Upon checking again, the GA events shows in top banner slider and offer boxes. But for "Einloggen" or login popup, still no GA events there. Please see below screenshot for the events that show upon clicking the login popup.

![image](https://github.com/aemsites/888de/assets/165638341/d1c75bbb-c14a-4da1-bb40-649d0931b76a)

**Comment by kailasnadh790** [comment]
https://github.com/aemsites/888de/assets/53608019/d469a860-1978-40f4-9260-cf40199bd2e3

I am seeing events firing on click of images on login popup... there is no events defined on "Einloggen" even on the live site.

**Comment by jeric888williamhill** [comment]
Hi @kailasnadh790, let's wait for issue #192 to be fixed. Maybe this is the reason why the GA events does not fire correctly on my end.

**Comment by kailasnadh790** [comment]
@jeric888williamhill yes..that makes sense... @dave-fink can you take a look ?

**Comment by dave-fink** [comment]
This has been resolved. 

@rafim888 We see that it is not working on the 404 page, but that is because the SmartButton function is not defined for that page. We believe this must be a CDN level configuration. 

![image](https://github.com/aemsites/888de/assets/138233107/c0bee2a3-f6ba-495c-acd8-6f4dd8f594d3)

**Comment by rafim888** [comment]
events on login popup are fixed

**Comment by kailasnadh790** [comment]
@rafim888 I still see the issue and console errors on the 404 page eg: https://eds-www.888.de/errorpage/

![image](https://github.com/aemsites/888de/assets/53608019/9ec84025-6740-441c-99a1-c2bca3352695)

**Comment by rafim888** [comment]
@yarivfel (and the team) will have a look

**Comment by yarivfel** [comment]
From a brief look there is no
/scripts/888-main.js
on the 404 page.
Also I see the onclick contain this character ‘ instead of ' 
I think this should resolve the problems.

**Comment by kailasnadh790** [comment]
thanks for the findings @yarivfel ..now, the smartButtons are functional. However, we still don't see events getting triggered. Can you please have a look at what is missing?

**Comment by yarivfel** [comment]
Please change in the onclick instead of "Gtm.Trigger" to be "window.googleTagManager.trigger"

**Comment by yarivfel** [comment]
@kailasnadh790 
Also found and issue with the main image on wide screen
![image](https://github.com/aemsites/888de/assets/158459884/096deb68-a479-4f83-8ab2-0fc2a3182484)

**Comment by kailasnadh790** [comment]
@yarivfel will fix these. But why is the buttons in the login popup not triggering GA events just on the error page? even with window.googleTagManager.trigger ?

**Comment by kailasnadh790** [comment]
@yarivfel Styling issues are fixed. and script is changed as suggested. Still not seeing GA events.

**Comment by kailasnadh790** [comment]
@yarivfel It was found that datalayer object definition was missing. Now that is added, atleast login popup icon tracking is working...still, tracking of button clicks on the body not working.

**Comment by yarivfel** [comment]
I got lost now.
where should I test it now?

**Comment by helms-charity** [comment]
@yarivfel you can test at https://stage-www.888.de/aaa/ (or similar nonsense page).
![image](https://github.com/aemsites/888de/assets/3883795/b2656b18-4be6-4047-b842-3e304c6b1baa)

**Comment by yarivfel** [comment]
Thanks
checking on that URL I do get the events.
![image](https://github.com/aemsites/888de/assets/158459884/d8b070c1-d113-410c-82f8-7290d11fd34d)
But I do understand now that this works only if I wait for few seconds then click on the CTA's.
If I click the CTA's as soon the page load, it's not working.

**Comment by kailasnadh790** [comment]
@yarivfel yes..that is expected. In AEM, we are loading GTM after 3s to improve page performance.
