### ISSUE TITLE
Login links under "Einloggen" target="_self" is being overridden

### ISSUE THREAD

**Issue by ByronA-888WHG** [aemsites/888de#192]
Hello @helms-charity,
Please look at the issue below

1. EDS "Einloggen" Poker, Sport and Casino opens additional homepage tab for each brands

Step to replicate
1. Open Einloggen
2. Click on each brands
![2024-04-04_18-24-33](https://github.com/aemsites/888de/assets/165295931/5e5be3aa-51e9-4aaf-bb21-38dbce6779f7)

Thanks !

**Comment by helms-charity** [comment]
- [ ]  **Working**: same-domain links open in self (same tab) by default, but can be overridden by authoring `target=_blank` in the linked text;
- [ ] **Defect**: external links have `target="_blank"` programmatically added (by design), but when authoring the target to be something OTHER than `_blank` it gets overridden to  `target="_blank"`

**Comment by dave-fink** [comment]
@ByronA-888WHG This has been resolved, please retest.

**Comment by ByronA-888WHG** [comment]
Hello @dave-fink,
Upon retesting the issue still persist

https://github.com/aemsites/888de/assets/165295931/0930d565-2b5e-4846-8652-7255fd965851

**Comment by dave-fink** [comment]
Please try now.  

Related to #191

**Comment by ByronA-888WHG** [comment]
Hello @dave-fink,
Upon retest, this works as intended now.
Thank you!
