### ISSUE TITLE
Homepage: [Tablet devices] "Bonusregelung" hyperlink positioning is too low in the top banner 

### ISSUE THREAD

**Issue by jeric888williamhill** [aemsites/888de#210]
Hi @helms-charity,

Please see bug details below:

Steps to Reproduce:
1. Access https://eds-www.888.de/ using tablet devices.
2. Notice that "Bonusregelung" hyperlink positioning is too low in the top banner.

Note: Does not happen in live site. Ipad 9th gen was the device used for this test.

![image](https://github.com/aemsites/888de/assets/165638341/e744015b-fba2-409c-be53-be248a6d212d)

**Comment by kailasnadh790** [comment]
@jeric888williamhill this should be fixed now. Please validate.

**Comment by jeric888williamhill** [comment]
@kailasnadh790 , partially fixed. The word "Bonusregelung" is not underlined making it not distinguishable as a hyperlink.
![image](https://github.com/aemsites/888de/assets/165638341/b6bbeb3c-fc7a-49b4-bb75-e5483c6e57f6)

**Comment by kailasnadh790** [comment]
@jeric888williamhill it is not underlined on the live site. Do you want to make this underlined for the new site? if so, do you want it to be that way on all the devices?
![image](https://github.com/aemsites/888de/assets/53608019/32c2bac1-1503-446d-84e5-43d3f8e6f0d7)

**Comment by jeric888williamhill** [comment]
Hi @kailasnadh790,

It is underlined on the live site using a real device. Ipad 9th gen was used for this testing.

![image](https://github.com/aemsites/888de/assets/165638341/e1839b6b-f768-4c73-9559-d24cbbf399b3)

**Comment by kailasnadh790** [comment]
This is fixed. Please validate.

**Comment by jeric888williamhill** [comment]
Fixed/verified. Closing this issue.
Thanks!
